### ISSUE TITLE
Servertime not correct?

### ISSUE THREAD

**Issue by thibautvincent** [osoc16/kleinpas#6]
It's 7.02 and want to add a new reminder but the day already passed...

<img width="1680" alt="screen shot 2016-07-28 at 7 02 12 am" src="https://cloud.githubusercontent.com/assets/9417678/17201729/5fee47ec-5491-11e6-9bbc-fecbe47a01ea.png">

**Comment by AngryMoustache** [comment]
This is fine, you wont ask to be reminded ON the day of the event, so this isnt an issue :)
